### ISSUE TITLE
Can I safely replace #'my-middleware with my-middleware in line 119 of main-clj?

### ISSUE THREAD

**Issue by kloimhardt** [seancorfield/usermanager-example#1]
Dear Sean, thank you for usermanager-example.
In trying to understand your code, I re-read the chapter "Def, Symbols, and Vars" in the book "Getting Clojure". Then I did the following repl experiment:

```
user=> (def f (fn [x] (* x x)))
#'user/f
user=> (def g #'f)
#'user/g
user=> (g 2)
4
user=> (def h f)
#'user/h
user=> (h 2)
4
```

So,`(g 2)` and `(h 2)` being the same, I changed `#'my-middleware` to `my-middleware` in your code. The result is, that usermanager-example seems to work flawlessly.

I tried another repl experiment:

```
user=> (def a 1)
#'user/a
user=> (def b #'a)
#'user/b
user=> b
#'user/a
user=> (def c a)
#'user/c
user=> c
1
```
From this, I understand that sometimes it might be useful to pass the variable #'a instad of the bound value 1 in some function call. It is useful, because the symbol a is bound to a number and not to a (fn ...). But, as I tried to explain above, if some symbol f is bound to a (fn ...), I do not understand the use of passing the var #'f instead of the (fn ...) bound to f.

So, to rephrase my question: did you write this #'my-middleware instead of just my-middleware only because it is "more correct" in some sense, because it is more idiomatic, because it is better style? Or is it necessary for some reason?

I hope that you found the patience to bear with my problem and read to this end, and I ask for your answer in the hope to understand usermanager-example a bit better.

**Comment by seancorfield** [comment]
If you use the bare symbol in a _non-function_ position its current value will be compiled into the code that uses it, i.e., its definition at the time the form is compiled. That means you that if you redefine the function, the running code continues to use the old definition.

In order to make life easy for working with the REPL, using a Var means that you can redefine the function and the new definition will be picked up immediately (without needing to recompile things and restart the web app).

See this section of the official Clojure beginners' REPL guide for more detail: https://clojure.org/guides/repl/enhancing_your_repl_workflow#writing-repl-friendly-programs

**Comment by kloimhardt** [comment]
Thank you for this clear and elaborate answer. It was very helpful. Did you consider adding this information to the comments in the code? Or maybe it is really just me who was not able to make this (albeit on clojure.org well documented) connection of using vars and repl driven development. I wrongly suspected a completely different, perhaps ring-specific, reason.

**Comment by seancorfield** [comment]
Good idea, since I am often recommending this repo to beginner. I've added comments about it in this commit https://github.com/seancorfield/usermanager-example/commit/ad563770acc666dea3784fbb777116e839149d5c

**Comment by kloimhardt** [comment]
Indeed, I think your usermanager-example is THE way for sincere beginners. I made my own take on the beginner topic using some graphical interface, but this approach has limitations, not the least because it is the kind of game no-one plays in production. Whereas one pillar which usermanager-example rests upon is that it is the state of play. That you are game for updating the comments upon questions from new users is, I think, the other pillar of this approach. For you it must be really annoying to add a comment to explain some (for you) trivial #' character. Moreover, in selflessly pointing to the authoritative source, you choose to play the role of a kind of lawyer (as opposed to Authority with capital A). This has such an incredible democratic appeal which is very healthy to any community. A feat not so many (only few?, certainly not me) can achieve in an 8 line comment. I do not know whether or not I should hope that more people are going to ask (trivial-for-you) questions. In any case: thank you for actually taking the effort and going THE way, the most fruitful way, to make Clojure accessible.
