### ISSUE TITLE
Unused parameter in WebServer component

### ISSUE THREAD

**Issue by michaelrkytch** [seancorfield/usermanager-example#12]
The 'server' parameter of WebServer in usermanager.main is unused.

**Comment by seancorfield** [comment]
Thanks for the PR. It was leftover from an earlier version where you could specify `:jetty` or `:http-kit` to show how easy it was to swap web servers -- but it just added unnecessary noise to the example so I took that logic (and documentation) out... but missed the `server` parameter!

**Comment by michaelrkytch** [comment]
Cool.  This project was very helpful in putting together my first Clojure web app.  I used a slightly different stack, but this helped me organize components and improve my workflow.
