### ISSUE TITLE
Small gotcha when trying out project due to namespace change

### ISSUE THREAD

**Issue by gleenn** [seancorfield/usermanager-example#17]
Looks like the "polylith" branch suggests running:

`clj -M:dev -m usermanager.web.main`

but a newbie like myself cloned the repo and immediately was put onto the "develop" branch where you have to run:

`clj -M:dev -m usermanager.main`

This might be a very small detail but probably everyone trips over this when trying this cool project out for the first time. I see you even say to run using the "polylith" branch but it's a little buried.

IMHO make those two branches align so everyone doesn't have to figure that out.

Very cool project example though, thanks @seancorfield !

**Comment by seancorfield** [comment]
Ah, yes, that would be a great addition to the README!
